version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: alquilatusvehiculos-0.0.1-SNAPSHOT.jar # Verificar de que el nombre de tu archivo JAR sea correcto
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/alquilatusvehiculos?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: alquilatusvehiculos
      MYSQL_ROOT_PASSWORD: 1234
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d # Asegúrate de que la ruta a tus scripts SQL sea correcta y accesible

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 1234
    depends_on:
      - db

volumes:
  db_data:
